name: region_codes_app
description: An simple console app to search region codes by cities
version: 1.0.0
repository: https://github.com/evendelger/region_codes_app

environment:
  sdk: ^3.0.5

dev_dependencies:
  lints: ^2.0.0
